


"""ecom_agentic_system.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N0k6Hzx4dr-k_Ry1vrESH-z3AWUebZFX
"""


# -*- coding: utf-8 -*-
import os
import requests
from crewai import Agent, Crew, Process, Task, LLM
from crewai.project import CrewBase, agent, crew, task
from crewai.tools import BaseTool
import streamlit as st


class DummyJSONTool(BaseTool):
    name: str = "DummyJSON API Tool"
    description: str = "Fetch products from DummyJSON using keyword search"

    def _run(self, query: str) -> str:
        try:
            url = f"https://dummyjson.com/products/search?q={query}"
            response = requests.get(url, timeout=10)
            response.raise_for_status()
            data = response.json()
            products = data.get("products", [])
            if not products:
                return "No products found for this keyword."
            return "\n".join([f"{p['title']} - ${p['price']} ({p['category']})" for p in products[:5]])
        except Exception as e:
            return f"Error: {str(e)}"


class FakeStoreTool(BaseTool):
    name: str = "FakeStore API Tool"
    description: str = "Fetch products from FakeStore by category"

    def _run(self, query: str) -> str:
        try:
            url = f"https://fakestoreapi.com/products/category/{query}"
            response = requests.get(url, timeout=10)
            response.raise_for_status()
            data = response.json()
            if not data:
                return "No products found for this category."
            return "\n".join([f"{p['title']} - ${p['price']} ({p['category']})" for p in data[:5]])
        except Exception as e:
            return f"Error: {str(e)}"


class EscuelajsTool(BaseTool):
    name: str = "Escuelajs API Tool"
    description: str = "Fetch products from Escuelajs API using keyword"

    def _run(self, query: str) -> str:
        try:
            url = f"https://api.escuelajs.co/api/v1/products?title={query}"
            response = requests.get(url, timeout=10)
            response.raise_for_status()
            data = response.json()
            if not data:
                return "No products found for this keyword."
            return "\n".join([f"{p['title']} - ${p['price']}" for p in data[:5]])
        except Exception as e:
            return f"Error: {str(e)}"



@CrewBase
class ResearchCrew:
    """Research crew for e-commerce product fetching and reporting"""

   
    agents_config = "config/configagents.yaml"
    tasks_config = "config/configtasks.yaml"

   
    @agent
    def research_master_agent(self) -> Agent:
        return Agent(
            tools=[DummyJSONTool(), FakeStoreTool(), EscuelajsTool()],
            verbose=True
        )

    @agent
    def llm_agent(self) -> Agent:
        return Agent(
            llm=LLM(
                model="gpt-4o-mini",
                temperature=0.7,
                api_key=st.secrets["OPENAI_API_KEY"]
            ),
            verbose=True
        )

    
    @task
    def research_task(self) -> Task:
        return Task()  

    @task
    def analysis_task(self) -> Task:
        output_dir = os.path.join(os.getcwd(), "output")
        os.makedirs(output_dir, exist_ok=True)
        return Task(output_file=os.path.join(output_dir, 'report.md'))  

   
    @crew
    def crew(self) -> Crew:
        return Crew(
            agents=self.agents,   
            tasks=self.tasks,     
            process=Process.sequential,
            verbose=True,
        )



st.title("E-Commerce Product Research and Analysis")
st.subheader("Powered by CrewAI")
st.write("Enter a keyword to search for products:")

in_put = st.text_input("Search Keyword", key="search_keyword")

if in_put:
    try:
        ans = ResearchCrew().crew().kickoff(inputs={"query": in_put})
        st.write(ans)
    except Exception as e:
        st.error(f"Error running CrewAI: {e}")
else:
    st.write("Please enter a keyword to search.")


    
